# Generated by Django 2.2.1 on 2019-05-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190515_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('women', '女')], max_length=10),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='skill',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='技能'),
        ),
    ]
